<a href="https://colab.research.google.com/github/sergioarnold87/Practica_Sergio/blob/main/Metodos_Directos_Sistemas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías necesarias

In [1]:
import numpy as np
import math

# Función Helper

In [2]:
def sustitucionAtras(Ab):
  """
  Esta función resuelve un sistema triangular superior mediante sustitución hacia atrás

  Args:
    Ab: Array bidimensional (Matriz ampliada del sistema triangular superior)
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  n = Ab.shape[0]
  x = np.empty(n)
  x[n - 1] = Ab[n - 1, n] / Ab[n - 1, n - 1]
  for i in range(n - 2, -1, -1):
    x[i] = (Ab[i, n] - np.sum(Ab[i, (i + 1):n] * x[(i + 1):n])) / Ab[i, i]

  return x

In [3]:
def sustitucionDelante(Ab):
  """
  Esta función resuelve un sistema triangular inferior mediante sustitución
  hacia delante

  Args:
    Ab: Array bidimensional (Matriz ampliada del sistema triangular inferior)

  Returns:
    x: Array unidimensional con la solución del sistema
  """
  n = Ab.shape[0]
  x = np.empty(n)
  x[0] = Ab[0, n] / Ab[0, 0]
  for i in range(1, n):
    x[i] = (Ab[i, n] - np.sum(Ab[i, :i] * x[:i])) / Ab[i, i]

  return x

# Ejemplo 1: Método de eliminación de Gauss para resolver un sistema lineal de ecuaciones
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **eliminación de Gauss** y resuelve el sistema resultante con matriz **triangular superior** por el método de **sustitución hacia atrás.**

In [4]:
Ab = [[1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2],
     [0, 1, 0, 4, -1, 3], 
     [1, 3, 1, 0, 5, 1]]
Ab = np.array(Ab)

In [5]:
print(Ab)

[[ 1  1 -3 -1 -2  2]
 [ 1  2  2  0  3  2]
 [ 1 -1  3  2  0  2]
 [ 0  1  0  4 -1  3]
 [ 1  3  1  0  5  1]]


In [6]:
def metodoGauss(Ab, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz 
  del sistema triangular superior y devuelve la solución al sistema calculada
  mediante sustitución hacia atrás

  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    verbose: Booleano para mostrar o no los resultados relevantes
  Returns:
    x: Array unidimensional con la solución del sistema

  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de filas de Ab
  n = Ab.shape[0]

  # Convertimos la matriz del sistema en triangular superior 
  for k in range(n - 1):
    p = k
    if Ab[k, k] == 0:
      for i in range(k + 1, n):
        if Ab[i, k] != 0:
          p = i
          break

    if p == k and Ab[k,k] == 0:
        print("El sistema no es compatible determinado")
        return
    
    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[k]
      Ab[k] = row

    for j in range(k + 1, n):
      m = Ab[j, k] / Ab[k, k]
      Ab[j] = Ab[j] - m  * Ab[k]

  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)

  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)

  # Resolvemos el sistema con sustitución hacia atrás
  x = sustitucionAtras(Ab)

  if verbose:
    print("X =", x)
  
  return x

In [7]:
x = metodoGauss(Ab, verbose = True)

Ab =
 [[ 1.          1.         -3.         -1.         -2.          2.        ]
 [ 0.          1.          5.          1.          5.          0.        ]
 [ 0.          0.         16.          5.         12.          0.        ]
 [ 0.          0.          0.          4.5625     -2.25        3.        ]
 [ 0.          0.          0.          0.          1.93150685 -1.57534247]]
Ab =
 [[ 1.          1.         -3.         -1.         -2.          2.        ]
 [ 0.          1.          5.          1.          5.          0.        ]
 [ 0.          0.         16.          5.         12.          0.        ]
 [ 0.          0.          0.          4.5625     -2.25        3.        ]
 [ 0.          0.          0.          0.          1.93150685 -1.57534247]]
X = [ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


In [8]:
B = [[0, 1, 0, 4, -1, 3],
     [1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2], 
     [1, 3, 1, 0, 5, 1]]
B = np.array(B)
y = metodoGauss(B)
print(y)

[ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


# ***Ejemplo 2: Sistema mal condicionado***
Dado un sistema lineal $\mathbf{A}\mathbf{x}=\mathbf{b}$ mal condicionado, es decir $|\mathrm{det}(\mathbf{A})|<<1$, da la solución de sistema $\mathbf{x}$ usando el método de **eliminación de Gauss** y **sustitución hacia atrás** suponiendo que se trabaja com $m$ **dígitos significativos**.


In [11]:
Ab = [[0.010534, 0.02, -1],
      [1, 2, 3]]
Ab = np.array(Ab)

In [12]:
print(Ab)

[[ 0.010534  0.02     -1.      ]
 [ 1.        2.        3.      ]]


In [13]:
def signif(x, m = 0):
  """
  Esta función devuelve el número x con m dígitos significativos 

  Args:
    x: Float
    m: Int (Número de dígitos significtivos)

  Returns:
    Valor float x con m dígitos significativos
  """
  if x == 0:
    return 0
  else:
    return round(x, ndigits = m -1 - int(math.floor(math.log10(abs(x))))) 

In [14]:
# Convertimos la función signif a función universal
signif = np.frompyfunc(signif, 2, 1)

In [ ]:
def metodoGaussSignif(Ab, sig = 5,verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz 
  del sistema triangular superior y devuelve la solución al sistema calculada
  mediante sustituciń hacia atrás

  Cada vez que hacemos un cálculo, nos quedamos con los sig dígitos significativos

  Args:
    Ab: Array bidimensional de Numpy (Matriz ampliada del sitema)
    sig: Int que indica los dígitos significativos
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  # Pasamos todas las entradas del array bidimensional a tipio float
  Ab = signif(Ab.astype("float"), sig)
  # Número de filas de Ab
  n = Ab.shape[0]

  # Convertimos la matriz del sistema en triangular superior 
  for k in range(n-1):
    Ab = signif(Ab, sig)
    p = k
    if Ab[k, k] == 0:
      for i in range(k + 1, n):
        if Ab[i, k] !=0:
          p = i
          break

    if p == k and Ab[k,k] == 0:
      print("El sistema no es compatible determinado")
      return
  
    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[b]
      Ab[k] = row

    
