<a href="https://colab.research.google.com/github/sergioarnold87/Practica_Sergio/blob/main/Metodos_Directos_Sistemas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Librerías necesarias

In [29]:
import numpy as np
import math

# Función Helper

In [30]:
def sustitucionAtras(Ab):
  """
  Esta función resuelve un sistema triangular superior mediante sustitución hacia atrás

  Args:
    Ab: Array bidimensional (Matriz ampliada del sistema triangular superior)
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  n = Ab.shape[0]
  x = np.empty(n)
  x[n - 1] = Ab[n - 1, n] / Ab[n - 1, n - 1]
  for i in range(n - 2, -1, -1):
    x[i] = (Ab[i, n] - np.sum(Ab[i, (i + 1):n] * x[(i + 1):n])) / Ab[i, i]

  return x

In [31]:
def sustitucionDelante(Ab):
  """
  Esta función resuelve un sistema triangular inferior mediante sustitución
  hacia delante

  Args:
    Ab: Array bidimensional (Matriz ampliada del sistema triangular inferior)

  Returns:
    x: Array unidimensional con la solución del sistema
  """
  n = Ab.shape[0]
  x = np.empty(n)
  x[0] = Ab[0, n] / Ab[0, 0]
  for i in range(1, n):
    x[i] = (Ab[i, n] - np.sum(Ab[i, :i] * x[:i])) / Ab[i, i]

  return x

# Ejemplo 1: Método de eliminación de Gauss para resolver un sistema lineal de ecuaciones
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **eliminación de Gauss** y resuelve el sistema resultante con matriz **triangular superior** por el método de **sustitución hacia atrás.**

In [32]:
Ab = [[1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2],
     [0, 1, 0, 4, -1, 3], 
     [1, 3, 1, 0, 5, 1]]
Ab = np.array(Ab)

In [33]:
print(Ab)

[[ 1  1 -3 -1 -2  2]
 [ 1  2  2  0  3  2]
 [ 1 -1  3  2  0  2]
 [ 0  1  0  4 -1  3]
 [ 1  3  1  0  5  1]]


In [34]:
def metodoGauss(Ab, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz 
  del sistema triangular superior y devuelve la solución al sistema calculada
  mediante sustitución hacia atrás

  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    verbose: Booleano para mostrar o no los resultados relevantes
  Returns:
    x: Array unidimensional con la solución del sistema

  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de filas de Ab
  n = Ab.shape[0]

  # Convertimos la matriz del sistema en triangular superior 
  for k in range(n - 1):
    p = k
    if Ab[k, k] == 0:
      for i in range(k + 1, n):
        if Ab[i, k] != 0:
          p = i
          break

    if p == k and Ab[k,k] == 0:
        print("El sistema no es compatible determinado")
        return
    
    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[k]
      Ab[k] = row

    for j in range(k + 1, n):
      m = Ab[j, k] / Ab[k, k]
      Ab[j] = Ab[j] - m  * Ab[k]

  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)

  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)

  # Resolvemos el sistema con sustitución hacia atrás
  x = sustitucionAtras(Ab)

  if verbose:
    print("X =", x)
  
  return x

In [35]:
x = metodoGauss(Ab, verbose = True)

Ab =
 [[ 1.          1.         -3.         -1.         -2.          2.        ]
 [ 0.          1.          5.          1.          5.          0.        ]
 [ 0.          0.         16.          5.         12.          0.        ]
 [ 0.          0.          0.          4.5625     -2.25        3.        ]
 [ 0.          0.          0.          0.          1.93150685 -1.57534247]]
Ab =
 [[ 1.          1.         -3.         -1.         -2.          2.        ]
 [ 0.          1.          5.          1.          5.          0.        ]
 [ 0.          0.         16.          5.         12.          0.        ]
 [ 0.          0.          0.          4.5625     -2.25        3.        ]
 [ 0.          0.          0.          0.          1.93150685 -1.57534247]]
X = [ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


In [36]:
B = [[0, 1, 0, 4, -1, 3],
     [1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2], 
     [1, 3, 1, 0, 5, 1]]
B = np.array(B)
y = metodoGauss(B)
print(y)

[ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


# ***Ejemplo 2: Sistema mal condicionado***
Dado un sistema lineal $\mathbf{A}\mathbf{x}=\mathbf{b}$ mal condicionado, es decir $|\mathrm{det}(\mathbf{A})|<<1$, da la solución de sistema $\mathbf{x}$ usando el método de **eliminación de Gauss** y **sustitución hacia atrás** suponiendo que se trabaja com $m$ **dígitos significativos**.


In [37]:
Ab = [[0.010534, 0.02, -1],
      [1, 2, 3]]
Ab = np.array(Ab)

In [38]:
print(Ab)

[[ 0.010534  0.02     -1.      ]
 [ 1.        2.        3.      ]]


In [39]:
def signif(x, m = 0):
  """
  Esta función devuelve el número x con m dígitos significativos 

  Args:
    x: Float
    m: Int (Número de dígitos significtivos)

  Returns:
    Valor float x con m dígitos significativos
  """
  if x == 0:
    return 0
  else:
    return round(x, ndigits = m -1 - int(math.floor(math.log10(abs(x))))) 

In [40]:
# Convertimos la función signif a función universal
signif = np.frompyfunc(signif, 2, 1)

In [41]:
def metodoGaussSignif(Ab, sig = 5, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz 
  del sistema triangular superior y devuelve la solución al sistema calculada
  mediante sustitución hacia atrás

  Cada vez que hacemos un cálculo, nos quedamos con los sig dígitos signficativos

  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    sig: Int que indica los dígitos significativos
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = signif(Ab.astype("float"), sig)
  # Número de filas de Ab
  n = Ab.shape[0]

  # Convertimos la matriz del sistema en triangular superior
  for k in range(n - 1):
    Ab = signif(Ab, sig)
    p = k
    if Ab[k, k] == 0:
      for i in range(k + 1, n):
        if Ab[i, k] != 0:
          p = i
          break

    if p == k and Ab[k,k] == 0: 
        print("El sistema no es compatible determinado")
        return

    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[k]
      Ab[k] = row

    for j in range(k + 1, n):
      m = signif(signif(Ab[j, k], sig) / signif(Ab[k, k], sig), sig)
      Ab[j] = signif(Ab[j] - signif(m * Ab[k], sig), sig)
  
  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)
  
  # Resolvemos el sistema con sustitución hacia atrás
  x = np.empty(n)
  x[n - 1] = signif(signif(Ab[n - 1, n], sig) / signif(Ab[n - 1, n - 1], sig), sig)
  for i in range(n - 2, -1, -1):
    x = signif(x, sig)
    suma = 0.0
    for j in range(i + 1, n):
      suma = signif(suma + signif(Ab[i, j] * x[j], sig), sig)
    x[i] = signif(signif(Ab[i, n] - suma, sig) / signif(Ab[i, i], sig), sig)

  if verbose:
    print("x =", x)
  
  return x

In [42]:
x = metodoGaussSignif(Ab, verbose = True)

Ab =
 [[0.010534 0.02 -1.0]
 [0 0.1014 97.931]]
x = [-1928.6 965.79]


# Ejemplo 3: Método de Gauss con pivotaje parcial

## Ejemplo 3.1: Método de Gauss con pivotaje parcial limitando el número de cifras significativas
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **eliminación de Gauss con pivotaje parcial** o con permutación de filas y resuelve el sistema resultante con matriz **triangular superior** por el método de **sustitución hacia atrás** suponiendo que se trabaja con $m$ **dígitos significativos**.

In [43]:
Ab = [[0.010534, 0.02, -1], 
     [1, 2, 3]]
Ab = np.array(Ab)

In [44]:
print(Ab)

[[ 0.010534  0.02     -1.      ]
 [ 1.        2.        3.      ]]


In [45]:
def pivotajeParcialSignif(Ab, sig = 5, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz
  del sistema triangular superior mediante Pivotaje Parcial y devuelve la solución al sistema
  calculada mediante sustitución hacia atrás 

  Cada vez que hacemos un cálculo, nos quedamos con los sig dígitos significativos

  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    sig: Int que indica los dígitos significativos
    verbose: Bolleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema 
  """
  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = signif(Ab.astype("float"), sig)
  # Número de filas de Ab
  n = Ab.shape[0]

  # Convertimos la matriz del sistema en triangular superior
  for k in range(n - 1):
    Ab = signif(Ab, sig)
    p = k+abs(Ab[k:, k]).argmax()

    if Ab[p, k] == 0:
      print("El sistema no es compatible determinado")
      return

    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[k]
      Ab[k] = row

    for j in range(k + 1, n):
      m = signif(signif(Ab[j, k], sig) / signif(Ab[k, k], sig), sig)
      Ab[j] = signif(Ab[j] - signif(m * Ab[k], sig), sig)
  
  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)
  
  # Resolvemos el sistema con sustitución hacia atrás
  x = np.empty(n)
  x[n - 1] = signif(signif(Ab[n - 1, n], sig) / signif(Ab[n - 1, n - 1], sig), sig)
  for i in range(n - 2, -1, -1):
    x = signif(x, sig)
    suma = 0.0
    for j in range(i + 1, n):
      suma = signif(suma + signif(Ab[i, j] * x[j], sig), sig)
    x[i] = signif(signif(Ab[i, n] - suma, sig) / signif(Ab[i, i], sig), sig)

  if verbose:
    print("x =", x)
  
  return x

In [46]:
x = pivotajeParcialSignif(Ab, verbose = True)

Ab =
 [[1.0 2.0 3.0]
 [0 -0.001068 -1.0316]]
x = [-1928.8 965.92]


## Ejemplo 3.2: Método de Gauss con Pivotaje Parcial
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **eliminación de Gauss con pivotaje parcial** o con permutación de filas y resuelve el sistema resultante con matriz **triangular superior** por el método de **sustitución hacia atrás.**

In [47]:
Ab = [[1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2],
     [0, 1, 0, 4, -1, 3], 
     [1, 3, 1, 0, 5, 1]]
Ab = np.array(Ab)

In [48]:
print(Ab)

[[ 1  1 -3 -1 -2  2]
 [ 1  2  2  0  3  2]
 [ 1 -1  3  2  0  2]
 [ 0  1  0  4 -1  3]
 [ 1  3  1  0  5  1]]


In [49]:
def pivotajeParcial(Ab, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz 
  del sistema triangular superior mediante Pivotaje Parcial y devuelve la 
  solución al sistema calculada mediante sustitución hacia atrás
  
  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de filas de Ab
  n = Ab.shape[0]

  # Convertimos la matriz del sistema en triangular superior
  for k in range(n - 1):
    p = k+abs(Ab[k:, k]).argmax()

    if Ab[p, k] == 0:
      print("El sistema no es compatible determinado")
      return

    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[k]
      Ab[k] = row

    for j in range(k + 1, n):
      m = Ab[j, k] / Ab[k, k]
      Ab[j] = Ab[j] - m * Ab[k]
  
  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)
  
  # Resolvemos el sistema con sustitución hacia atrás
  x = sustitucionAtras(Ab)

  if verbose:
    print("x =", x)
  
  return x

In [50]:
x = pivotajeParcial(Ab, verbose = True)

Ab =
 [[ 1.          1.         -3.         -1.         -2.          2.        ]
 [ 0.         -2.          6.          3.          2.          0.        ]
 [ 0.          0.         10.          4.          9.         -1.        ]
 [ 0.          0.          0.          4.3        -2.7         3.3       ]
 [ 0.          0.          0.          0.         -1.63953488  1.3372093 ]]
x = [ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


# Ejemplo 4: Método de Gauss con Pivotaje Maximal
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **eliminación de Gauss con pivotaje maximal** o con permutación de filas y columnas y resuelve el sistema resultante con matriz **triangular superior** por el método de **sustitución hacia atrás.**

In [51]:
Ab = [[1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2],
     [0, 1, 0, 4, -1, 3], 
     [1, 3, 1, 0, 5, 1]]
Ab = np.array(Ab)

In [52]:
print(Ab)

[[ 1  1 -3 -1 -2  2]
 [ 1  2  2  0  3  2]
 [ 1 -1  3  2  0  2]
 [ 0  1  0  4 -1  3]
 [ 1  3  1  0  5  1]]


In [53]:
def pivotajeMaximal(Ab, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b en otro equivalente con matriz 
  del sistema triangular superior mediante Pivotaje Maximal y devuelve la 
  solución al sistema calculada mediante sustitución hacia atrás
  
  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de variables del sistema
  n = Ab.shape[0]
  # Hay que recordar los cambios de columnas realizados
  x_index = np.array(range(n)) #[0, 1, 2, ..., n-1]

  # Convertimos la matriz del sistema en triangular superior
  for k in range(n - 1):
    (p, q) = np.where(abs(Ab[k:, k:-1]) == abs(Ab[k:, k:-1]).max()) # (i_max, j_max)

    p = p[0]
    q = q[0]
    
    p+=k
    q+=k

    if Ab[p, q] == 0:
      print("El sistema no es compatible determinado")
      return

    # Cambiamos las filas si es necesario
    if p != k:
      row = Ab[p].copy()
      Ab[p] = Ab[k]
      Ab[k] = row

    # Cambiamos las columnas si es necesario y guardamos el cambio realizado
    if q != k:
      col = Ab[:, q].copy()
      Ab[:, q] = Ab[:, k]
      Ab[:, k] = col
      
      val = x_index[k]
      x_index[k] = x_index[q]
      x_index[q] = val

    # Hacemos ceros por debajo del pivote  
    for j in range(k + 1, n):
      m = Ab[j, k] / Ab[k, k]
      Ab[j] = Ab[j] - m * Ab[k]
  
  # Mostramos, si verbose = True, la matriz triangular superior resultante
  if verbose:
      print("Ab =\n", Ab)
      print("X_index =", x_index)

  # Resolvemos el sistema con sustitución hacia atrás
  x = sustitucionAtras(Ab)
    
  # Reordenamos el array de soluciones invirtiendo los cambios de columnas realizados  
  x = x[np.argsort(x_index)]
  
  if verbose:
    print("x =", x)
  
  return x

In [54]:
x = pivotajeMaximal(Ab, verbose = True)

Ab =
 [[ 5.          0.          1.          1.          3.          1.        ]
 [ 0.          4.          0.2         0.2         1.6         3.2       ]
 [ 0.          0.          2.9         0.9        -1.8         0.4       ]
 [ 0.          0.          0.          2.24137931  1.01724138  3.55172414]
 [ 0.          0.          0.          0.          1.08461538  1.26153846]]
X_index = [4 3 2 0 1]
x = [ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


# Ejemplo 5: Descomposición $LU$
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **descomposición $LU$** y da la solución del sistema usando la descomposición anterior.

In [55]:
Ab = [[1, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2],
     [0, 1, 0, 4, -1, 3], 
     [1, 3, 1, 0, 5, 1]]
Ab = np.array(Ab)

In [56]:
print(Ab)

[[ 1  1 -3 -1 -2  2]
 [ 1  2  2  0  3  2]
 [ 1 -1  3  2  0  2]
 [ 0  1  0  4 -1  3]
 [ 1  3  1  0  5  1]]


In [57]:
def LU(A, verbose = False):
  """
  Esta función realiza la descomposición LU de la matriz cuadrada
  
  Args:
    A: Array bidimensional de numpy (Matriz cuadrada)
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    (L, U): Tupla de arrays bidimensionales
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  A = A.astype("float")
  # Número de filas de A
  n = A.shape[0]
  # Inicializamos las matrices L y U
  L = np.zeros((n, n))
  U = np.zeros((n, n))

  # Calculamos la primera fila de U y la primera columna de L
  U[0, 0] = A[0, 0]
  for i in range(n):
    L[i, i] = 1
    U[0, i] = A[0, i]
    L[i, 0] = A[i, 0] / U[0, 0]

  # Calculamos la fila i-ésima de L y la columna i-ésima de U
  for i in range(1, n): 
    sum = 0
    for k in range(i):
      sum += L[i, k] * U[k, i]
    U[i, i] = A[i, i] - sum
    for j in range(i + 1, n):
      sum = 0
      for k in range(i):
        sum += L[i, k] * U[k, j]
      U[i, j] = A[i, j] - sum
      sum = 0
      for k in range(i):
        sum += L[j, k] * U[k, i]
      L[j, i] = 1 / U[i, i] * (A[j, i] - sum)

  if verbose:
    print("L =\n", L)
    print("U =\n", U)

  return (L, U)

In [58]:
lu = LU(Ab[:, :-1], verbose = True)

L =
 [[ 1.          0.          0.          0.          0.        ]
 [ 1.          1.          0.          0.          0.        ]
 [ 1.         -2.          1.          0.          0.        ]
 [ 0.          1.         -0.3125      1.          0.        ]
 [ 1.          2.         -0.375       0.19178082  1.        ]]
U =
 [[ 1.          1.         -3.         -1.         -2.        ]
 [ 0.          1.          5.          1.          5.        ]
 [ 0.          0.         16.          5.         12.        ]
 [ 0.          0.          0.          4.5625     -2.25      ]
 [ 0.          0.          0.          0.          1.93150685]]


In [59]:
def metodoLU(Ab, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b al sistema equivalente 
  LUx = b de modo que primero resuelve el sistema triangular inferior Ly = b y
  finalmente resuelve el sistema triangular superior Ux = y. Devuelve la 
  solución del segundo sistema
  
  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de filas y columnas de la matriz de coeficientes
  n = Ab.shape[0]
  
  # Obtenemos matriz de coeficientes y vector de términos independientes
  A = Ab[:, :-1].copy()
  b = Ab[:, -1].copy()
  b = b.reshape((n, 1))

  # Obtenemos la descomposición LU
  L, U = LU(A, verbose = verbose)
  
  # Resolvemos el sistema triangular inferior Ly = b
  Lb = np.concatenate((L, b), axis = 1)
  y = sustitucionDelante(Lb)

  if verbose:
    print("y =", y)  

  # Resolvemos el sistema triangular superior Ux = y
  y = y.reshape((n, 1))
  Uy = np.concatenate((U, y), axis = 1)
  x = sustitucionAtras(Uy)

  if verbose:
    print("x =", x)

  return x

In [60]:
x = metodoLU(Ab, verbose = True)

L =
 [[ 1.          0.          0.          0.          0.        ]
 [ 1.          1.          0.          0.          0.        ]
 [ 1.         -2.          1.          0.          0.        ]
 [ 0.          1.         -0.3125      1.          0.        ]
 [ 1.          2.         -0.375       0.19178082  1.        ]]
U =
 [[ 1.          1.         -3.         -1.         -2.        ]
 [ 0.          1.          5.          1.          5.        ]
 [ 0.          0.         16.          5.         12.        ]
 [ 0.          0.          0.          4.5625     -2.25      ]
 [ 0.          0.          0.          0.          1.93150685]]
y = [ 2.          0.          0.          3.         -1.57534247]
x = [ 1.05673759  1.16312057  0.53191489  0.25531915 -0.81560284]


# Ejemplo 6: Descomposición $LU$ con matrices de permutación
Dado un sistema lineal de la forma $\mathbf{A}\mathbf{x}=\mathbf{b}$ que suponemos **compatible determinado**, es decir, con solución única, devuelve la solución del sistema usando el método de **descomposición $LU$** usando **matrices de permutación** y da la solución del sistema usando la descomposición anterior.


In [61]:
Ab = [[0, 1, -3, -1, -2, 2], 
     [1, 2, 2, 0, 3, 2], 
     [1, -1, 3, 2, 0, 2],
     [0, 1, 0, 4, -1, 3], 
     [1, 3, 1, 0, 5, 1]]
Ab = np.array(Ab)

In [62]:
print(Ab)

[[ 0  1 -3 -1 -2  2]
 [ 1  2  2  0  3  2]
 [ 1 -1  3  2  0  2]
 [ 0  1  0  4 -1  3]
 [ 1  3  1  0  5  1]]


In [63]:
def P_LU(A, permutations = None, verbose = False):
  """
  Esta función realiza la descomposición LU de la matriz cuadrada
    realizando las permutaciones indicadas
  
  Args:
    A: Array bidimensional de numpy (Matriz cuadrada)
    permutations: Lista de tuplas de permutaciones de filas
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    (P, L, U): Tupla de arrays bidimensionales
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  A = A.astype("float")
  # Número de filas de A
  n = A.shape[0]
  # Inicializamos las matrices P, L y U
  P = np.identity(n)
  L = np.zeros((n, n))
  U = np.zeros((n, n))
  
  # Permutamos filas en caso de que sea necesario
  if permutations is not None:
    for (i, j) in permutations:
      row = P[i].copy()
      P[i] = P[j]
      P[j] = row

  A = P.dot(A)

  if verbose:
    print("P =\n", P)

  L, U = LU(A, verbose = verbose)

  return (P, L, U)

In [64]:
lu = P_LU(Ab[:, :-1], permutations = [(0,4)], verbose = True)

P =
 [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
L =
 [[ 1.   0.   0.   0.   0. ]
 [ 1.   1.   0.   0.   0. ]
 [ 1.   4.   1.   0.   0. ]
 [ 0.  -1.  -0.5  1.   0. ]
 [ 0.  -1.   1.  -0.6  1. ]]
U =
 [[ 1.   3.   1.   0.   5. ]
 [ 0.  -1.   1.   0.  -2. ]
 [ 0.   0.  -2.   2.   3. ]
 [ 0.   0.   0.   5.  -1.5]
 [ 0.   0.   0.   0.  -7.9]]


In [65]:
def metodoPLU(Ab, permutations = None, verbose = False):
  """
  Esta función transforma un sistema lineal Ax = b al sistema equivalente 
  LUx = b de modo que primero resuelve el sistema triangular inferior Ly = b y
  finalmente resuelve el sistema triangular superior Ux = y. Devuelve la 
  solución del segundo sistema.

  También tiene en cuenta una posible permutación de filas, de modo que en este
  caso transforma el sistema PAx = Pb al sistema equivalente LUx = Pb y
  resuelve los sistemas triangulares resultantes para obtener la solución del 
  sistema.
  
  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    permutations: Lista de tuplas de permutaciones de filas
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """

  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de filas y columnas de la matriz de coeficientes
  n = Ab.shape[0]
  
  # Obtenemos matriz de coeficientes y vector de términos independientes
  A = Ab[:, :-1].copy()
  b = Ab[:, -1].copy()
  b = b.reshape((n, 1))

  # Obtenemos la descomposición LU
  P, L, U = P_LU(A, permutations = permutations, verbose = verbose)
  b = P.dot(b)
  
  # Resolvemos el sistema triangular inferior Ly = b
  Lb = np.concatenate((L, b), axis = 1)
  y = sustitucionDelante(Lb)

  if verbose:
    print("y =", y)
  
  # Resolvemos el sistema triangular superior Ux = y
  y = y.reshape((n, 1))
  Uy = np.concatenate((U, y), axis = 1)
  x = sustitucionAtras(Uy)

  if verbose:
    print("x =", x)

  return x

In [66]:
x = metodoPLU(Ab, permutations = [(0, 4)], verbose = True)

P =
 [[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]
L =
 [[ 1.   0.   0.   0.   0. ]
 [ 1.   1.   0.   0.   0. ]
 [ 1.   4.   1.   0.   0. ]
 [ 0.  -1.  -0.5  1.   0. ]
 [ 0.  -1.   1.  -0.6  1. ]]
U =
 [[ 1.   3.   1.   0.   5. ]
 [ 0.  -1.   1.   0.  -2. ]
 [ 0.   0.  -2.   2.   3. ]
 [ 0.   0.   0.   5.  -1.5]
 [ 0.   0.   0.   0.  -7.9]]
y = [ 1.   1.  -3.   2.5  7.5]
x = [ 1.88607595  1.18987342  0.29113924  0.21518987 -0.94936709]


In [67]:
def metodoPLU(Ab, permutations = None, verbose = False):
  """
  Ésta función transforma un sistema lineal Ax = b al sistema  equivalente LUx = b de modo
  que primero resuelve el sistema triangular inferior Ly = b y finalmente resuelve 
  el sistema triangular superior Ux = y. Devuelve la solución del segundo sistema.

  También tiene en cuenta una posible permutación de filas, de modo que en este
  caso transforma el sistem a PAx = Pb al sistema equivalente LUx = Pb y resuelve
  los sistemas triangulares resultantes para obtener la solución del sistema.

  Args:
    Ab: Array bidimensional de numpy (Matriz ampliada del sistema)
    permutations: Lista de tuplas de permutaciones de filas
    verbose: Booleano para mostrar o no los resultados relevantes

  Returns:
    x: Array unidimensional con la solución del sistema
  """
  # Pasamos todas las entradas del array bidimensional a tipo float
  Ab = Ab.astype("float")
  # Número de filas y columnas de la matriz 

SyntaxError: ignored